apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - endpoints
      - secrets
      - namespaces
      - services
      - events
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
